### ISSUE TITLE
CT: Error: Assertion failed: cannot initialize twice

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#149]
```
calculus-grapher : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672666915809/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1672666915809%22%2C%22timestamp%22%3A1672668614059%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: cannot initialize twice
Error: Assertion failed: cannot initialize twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1672666915809/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:218:14)
at initializePhetioObject (Node.ts:6308:10)
at initializePhetioObject (Node.ts:6298:9)
at mutate (GraphsNode.ts:209:9)
at (CalculusGrapherScreenView.ts:96:22)
at (DerivativeScreenView.ts:33:4)
at (DerivativeScreen.ts:36:53)
at createView (Screen.ts:303:22)
at initializeView (Sim.ts:881:15)
id: Bayes Puppeteer
Snapshot from 1/2/2023, 8:41:55 AM
```

**Comment by veillette** [comment]
It is not the first time I make this mistake. Fix coming.

**Comment by veillette** [comment]
Fixed. above. Closing
