### ISSUE TITLE
CT phetioID already registered: 

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#217]
```
calculus-grapher : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675248735342/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1675248735342%22%2C%22timestamp%22%3A1675250663543%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.widthControl.curveNode
Error: Assertion failed: phetioID already registered: calculusGrapher.derivativeScreen.view.controlPanel.curveManipulationControls.widthControl.curveNode
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1675248735342/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:658:35)
at phetioObjectAdded (phetioEngine.ts:1221:19)
at addPhetioObject (Tandem.ts:198:37)
at addPhetioObject (PhetioObject.ts:332:16)
at initializePhetioObject (Node.ts:6320:10)
at initializePhetioObject (Node.ts:6310:9)
at mutate (Node.ts:830:11)
at (CurveManipulationDisplayNode.ts:50:4)
at (CurveManipulationWidthControl.ts:26:22)
id: Bayes Puppeteer
Snapshot from 2/1/2023, 3:52:15 AM
```

**Comment by veillette** [comment]
The tandem curveNode is already assigned.

**Comment by veillette** [comment]
A fix is coming.

**Comment by pixelzoom** [comment]
Thanks for handling this @veillette. CT looks happy, so closing.

**Comment by veillette** [comment]
I misunderstood the problem, and corrected the

**Comment by veillette** [comment]
I'm confident that this is fixed. Closing
