### ISSUE TITLE
CT assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#25]
```
calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594287657758%22%2C%22timestamp%22%3A1594288409572%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:70:17
at Object.forEachAdjacentPair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/CalculusGrapherUtils.js:31:7)
at IntegralCurve.updateIntegral (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:69:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:41:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/OriginalCurve.js:201:30)
id: Bayes Chrome
Snapshot from 7/9/2020, 3:40:57 AM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1594287657758%22%2C%22timestamp%22%3A1594288360932%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:70:17
at Object.forEachAdjacentPair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/CalculusGrapherUtils.js:31:7)
at IntegralCurve.updateIntegral (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:69:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:41:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/OriginalCurve.js:201:30)
id: Bayes Chrome
Snapshot from 7/9/2020, 3:40:57 AM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1594287657758%22%2C%22timestamp%22%3A1594294045215%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:70:17
at Object.forEachAdjacentPair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/CalculusGrapherUtils.js:31:7)
at IntegralCurve.updateIntegral (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:69:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/IntegralCurve.js:41:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594287657758/calculus-grapher/js/common/model/OriginalCurve.js:201:30)
id: Bayes Chrome
Snapshot from 7/9/2020, 3:40:57 AM
```

**Comment by brandonLi8** [comment]
Thanks @KatieWoe.

**Comment by brandonLi8** [comment]
My guess is this happens when the user tilts the curve near the origin, which results in a vertical graph.

**Comment by brandonLi8** [comment]
Pushed a temporary fix in the commit above.

**Comment by brandonLi8** [comment]
#26 was addressed and ct is green. Closing.

**Comment by KatieWoe** [comment]
Seems to pop in and out of CT. Reopening.
```
calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1594829411982%22%2C%22timestamp%22%3A1594832715805%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/assert/js/assert.js:22:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/js/common/model/IntegralCurve.js:74:17
at Object.forEachAdjacentPair (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/js/common/CalculusGrapherUtils.js:31:7)
at IntegralCurve.updateIntegral (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/js/common/model/IntegralCurve.js:73:26)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/js/common/model/OriginalCurve.js:206:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594829411982/calculus-grapher/js/common/view/OriginalCurveNode.js:59:17)
id: Bayes Chrome
Snapshot from 7/15/2020, 10:10:11 AM
```

**Comment by brandonLi8** [comment]
I ran the [snap-shot](https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594840019960/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594840019960%22%2C%22timestamp%22%3A1594841753176%7D&brand=phet&ea&fuzz&memoryLimit=1000) for 15 minutes and was unable to reproduce. This seems like itls going to be hard to debug.

**Comment by brandonLi8** [comment]
Pushed a temporary fix in the commit above.

**Comment by KatieWoe** [comment]
Closing for https://github.com/phetsims/qa/issues/832. Feel free to reopen if this is in error.
