### ISSUE TITLE
CT y must be a finite number: NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#27]
```
calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594375074518%22%2C%22timestamp%22%3A1594388015128%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/assert/js/assert.js:22:13)
at Shape.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/kite/js/Shape.js:176:15)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/calculus-grapher/js/common/view/CurveNode.js:71:35)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/calculus-grapher/js/common/view/OriginalCurveNode.js:78:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/calculus-grapher/js/common/model/OriginalCurve.js:201:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594375074518/calculus-grapher/js/common/view/OriginalCurveNode.js:50:17)
id: Bayes Chrome
Snapshot from 7/10/2020, 3:57:54 AM
```

**Comment by brandonLi8** [comment]
Related to #25.

**Comment by brandonLi8** [comment]
I pushed a temporary fix that removed the tilt functionality. I'll revisit once #26 is addressed.

**Comment by brandonLi8** [comment]
#26 was addressed and ct is green. Closing.
