### ISSUE TITLE
CT y must be a finite number: NaN

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#30]
```
calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1595235095473%22%2C%22timestamp%22%3A1595237559822%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/assert/js/assert.js:22:13)
at Shape.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/kite/js/Shape.js:176:15)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/calculus-grapher/js/common/view/CurveNode.js:73:35)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/calculus-grapher/js/common/view/OriginalCurveNode.js:90:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/axon/js/TinyEmitter.js:69:53)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/axon/js/Emitter.js:33:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/axon/js/Emitter.js:58:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/calculus-grapher/js/common/model/OriginalCurve.js:207:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595235095473/calculus-grapher/js/common/view/OriginalCurveNode.js:59:17)
id: Bayes Chrome
Snapshot from 7/20/2020, 2:51:35 AM
```

**Comment by brandonLi8** [comment]
Pushed a temporary fix.

**Comment by KatieWoe** [comment]
This seems to have come back:
```
calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1611027948396%22%2C%22timestamp%22%3A1611071890878%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/assert/js/assert.js:25:13)
at Shape.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/kite/js/Shape.js:170:15)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/calculus-grapher/js/common/view/CurveNode.js:73:35)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/calculus-grapher/js/common/view/OriginalCurveNode.js:96:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Emitter.js:35:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/axon/js/Emitter.js:60:19)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/calculus-grapher/js/common/model/OriginalCurve.js:210:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611027948396/calculus-grapher/js/common/view/OriginalCurveNode.js:69:17)
id: Bayes Chrome
Snapshot from 1/18/2021, 8:45:48 PM
```

**Comment by KatieWoe** [comment]
Should this still be deferred?

**Comment by KatieWoe** [comment]
```
calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647607504180%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at Shape.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/kite/js/Shape.js:156:15)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/CurveNode.js:64:35)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/OriginalCurveNode.js:98:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Emitter.js:47:22)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/model/OriginalCurve.js:195:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/OriginalCurveNode.js:66:17)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/PressListener.js:352:10)
at DragListener._dragAction.PhetioAction.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/DragListener.js:172:36)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM

----------------------------------

calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647605832038%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at Shape.moveTo (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/kite/js/Shape.js:156:15)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/CurveNode.js:64:35)
at OriginalCurveNode.updateCurveNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/OriginalCurveNode.js:98:11)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/axon/js/Emitter.js:47:22)
at OriginalCurve.tiltToPosition (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/model/OriginalCurve.js:195:30)
at DragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/calculus-grapher/js/common/view/OriginalCurveNode.js:66:17)
at DragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/PressListener.js:352:10)
at DragListener._dragAction.PhetioAction.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/DragListener.js:172:36)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```

**Comment by veillette** [comment]
Still occuring on CT
````
calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663008464623/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663008464623%22%2C%22timestamp%22%3A1663028737530%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: y must be a finite number: NaN
Error: Assertion failed: y must be a finite number: NaN
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663008464623/assert/js/assert.js:28:13)
at assert (Shape.js:162:14)
at moveTo (CurveNode.js:71:34)
at updateCurveNode (OriginalCurveNode.js:96:10)
at listener (TinyEmitter.ts:95:8)
at emit (Emitter.ts:60:21)
at emit (OriginalCurve.js:210:29)
at tiltToPosition (OriginalCurveNode.js:69:16)
at _dragListener (PressListener.ts:528:9)
at call (DragListener.ts:309:35)
id: Bayes Puppeteer
Snapshot from 9/12/2022, 2:47:44 PM
````

**Comment by veillette** [comment]
All the CT failures invoke tiltToPosition, which is the likely point of failure. There are a lot of potential divisions by zero in tiltToPosition so I added a temporary assertion to it to see if that is not the point of failure.

**Comment by veillette** [comment]
I'll monitor CT for a few cycles to see if this new assertion gets triggered.

**Comment by veillette** [comment]
There has been several changes to the sim in the past two weeks.
CT has not been triggered by this assertion in the past week, so I'll go ahead and close this issue.
