### ISSUE TITLE
CT undefined not allowed for Node key mouseArea

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#33]
```
calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610062431559%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610077716384%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610092887823%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610109113151%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610075727095%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610089610524%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610104878407%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610120394625%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610065215974%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610078205824%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610093287569%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM

----------------------------------

calculus-grapher : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1610060004557%22%2C%22timestamp%22%3A1610109414016%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Undefined not allowed for Node key: mouseArea
Error: Assertion failed: Undefined not allowed for Node key: mouseArea
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5440:17
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/sherpa/lib/lodash-4.17.4.js:9359:14)
at GridNode.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/scenery/js/nodes/Node.js:5437:7)
at new GridNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/griddle/js/GridNode.js:111:10)
at new GraphNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/GraphNode.js:39:22)
at new CalculusGrapherScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/common/view/CalculusGrapherScreenView.js:35:23)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/view/IntroScreenView.js:25:5)
at IntroScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610060004557/calculus-grapher/js/intro/IntroScreen.js:27:33)
id: Bayes Chrome
Snapshot from 1/7/2021, 3:53:24 PM
```

**Comment by jonathanolson** [comment]
Was the intention of the removed code above to have no interaction with input? (pickable:false would be better). Or the default for "empty" mouse/touch areas is null.

**Comment by brandonLi8** [comment]
> Was the intention of the removed code above to have no interaction with input? (pickable:false would be better)

Thanks @jonathanolson. Unsure why but when I was running it earlier the grid in the background wasn't allowing drag inputs with the path in the foreground. But running it now is working. Closing.
