### ISSUE TITLE
CT x position cannot be zero

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#69]
```
calculus-grapher : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665054011867%22%2C%22timestamp%22%3A1665061543831%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: x position cannot be zero
Error: Assertion failed: x position cannot be zero
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/assert/js/assert.js:28:13)
at assert (OriginalCurve.ts:187:14)
at tiltToPosition (OriginalCurveNode.ts:91:16)
at _dragListener (PressListener.ts:528:9)
at call (DragListener.ts:309:35)
at apply (PhetioAction.ts:124:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
at inputEvent (Input.ts:1804:91)
at dispatchToListeners (Input.ts:1755:9)
id: Bayes Puppeteer
Snapshot from 10/6/2022, 5:00:11 AM

----------------------------------

calculus-grapher : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665054011867%22%2C%22timestamp%22%3A1665058552549%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: x position cannot be zero
Error: Assertion failed: x position cannot be zero
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/assert/js/assert.js:28:13)
at assert (OriginalCurve.ts:187:14)
at tiltToPosition (OriginalCurveNode.ts:91:16)
at _dragListener (PressListener.ts:528:9)
at call (DragListener.ts:309:35)
at apply (PhetioAction.ts:124:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
at inputEvent (Input.ts:1804:91)
at dispatchToListeners (Input.ts:1755:9)
id: Bayes Puppeteer
Snapshot from 10/6/2022, 5:00:11 AM

----------------------------------

calculus-grapher : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1665054011867%22%2C%22timestamp%22%3A1665059791805%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: x position cannot be zero
Error: Assertion failed: x position cannot be zero
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1665054011867/assert/js/assert.js:28:13)
at assert (OriginalCurve.ts:187:14)
at tiltToPosition (OriginalCurveNode.ts:91:16)
at _dragListener (PressListener.ts:528:9)
at call (DragListener.ts:309:35)
at apply (PhetioAction.ts:124:16)
at execute (DragListener.ts:460:21)
at drag (PressListener.ts:897:13)
at inputEvent (Input.ts:1804:91)
at dispatchToListeners (Input.ts:1755:9)
id: Bayes Puppeteer
Snapshot from 10/6/2022, 5:00:11 AM
```

**Comment by veillette** [comment]
I recently added dragBound to the drag listener. I suspect it may be related to it.

**Comment by veillette** [comment]
Sam correctly identified the issue. CT has been quiet since. Closing
