### ISSUE TITLE
CT: Uncaught Error: Assertion failed: t should be between 0 and 1 (inclusive):

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#92]
```
calculus-grapher : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668098278016/calculus-grapher/calculus-grapher_en.html?continuousTest=%7B%22test%22%3A%5B%22calculus-grapher%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1668098278016%22%2C%22timestamp%22%3A1668102682654%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: t should be between 0 and 1 (inclusive):
-3.4 and 1.0000000000000002: a:1.6000000000000014, b:3.840000000000003, c:-5.440000000000004
Error: Assertion failed: t should be between 0 and 1 (inclusive):
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1668098278016/assert/js/assert.js:28:13)
at assert (TransformedCurve.ts:280:22)
at drawFreeformToPosition (TransformedCurve.ts:424:11)
at userManipulatedCurve (OriginalCurve.ts:166:9)
at operatedCurve (OriginalCurveNode.ts:71:14)
```

**Comment by veillette** [comment]
This is related to recent work on freeform (#58)

**Comment by veillette** [comment]
One of the root is 1.0000000000000002 which is a tiny bit above 1. 
We could allow a tolerance for the bounds.

**Comment by veillette** [comment]
I'll keep an eye on CT to see if there are more egregious cases of failure.

**Comment by pixelzoom** [comment]
You could also use dot `Utils.clamp `to ensure that the value is in the bounds [0,1].

**Comment by veillette** [comment]
There hasn't been any other failures from CT. This indicates that the method to find the roots in the freeform algorithm is sound but that it may not pass CT because of rounding errors. 

The rounding error does not affect the position of the point, so we should let is slide but I'm reluctant to use `Utils.clamp` in the assertion as it may hide other problems.  I'll add an epsilon value to add tolerance to the bounds.

**Comment by veillette** [comment]
CT is no longer complaining. Closing.
